### ISSUE TITLE
 Looking for ending parenthsis match... error when checking mail

### ISSUE THREAD

**Issue by rajatjindal83** [jettero/net--imap--simple#5]
getting following error on interacting with IMAP server

[...re/perl5/Net/IMAP/Simple.pm line 1221 in sub _read_multiline] Looking for ending parenthsis match...

Perl 5.8.8, cent os 5.6

**Comment by jpswade** [comment]
:+1:

**Comment by jettero** [comment]
please submit issues on rt.cpan.org
